name: Generate Contribution Galaxy Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate Contribution Galaxy SVG
        run: |
          mkdir -p dist
          cat > dist/contribution-galaxy.svg << 'EOF'
          <svg width="800" height="400" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <radialGradient id="spaceGradient" cx="50%" cy="50%" r="50%">
                <stop offset="0%" style="stop-color:#0D1117;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#161B22;stop-opacity:1" />
              </radialGradient>
              
              <radialGradient id="starGlow" cx="50%" cy="50%" r="50%">
                <stop offset="0%" style="stop-color:#CFA98E;stop-opacity:1" />
                <stop offset="50%" style="stop-color:#E6B59A;stop-opacity:0.8" />
                <stop offset="100%" style="stop-color:#F1D3BF;stop-opacity:0" />
              </radialGradient>
              
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge> 
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
              
              <filter id="twinkle">
                <feGaussianBlur stdDeviation="1" result="coloredBlur"/>
                <feMerge> 
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            
            <!-- Space Background -->
            <rect width="800" height="400" fill="url(#spaceGradient)"/>
            
            <!-- Animated Stars Background -->
            <g id="stars">
              <circle cx="100" cy="50" r="1" fill="#CFA98E" opacity="0.8">
                <animate attributeName="opacity" values="0.3;1;0.3" dur="3s" repeatCount="indefinite"/>
              </circle>
              <circle cx="200" cy="80" r="1.5" fill="#E6B59A" opacity="0.6">
                <animate attributeName="opacity" values="0.2;0.9;0.2" dur="4s" repeatCount="indefinite"/>
              </circle>
              <circle cx="300" cy="60" r="1" fill="#F1D3BF" opacity="0.7">
                <animate attributeName="opacity" values="0.4;1;0.4" dur="2.5s" repeatCount="indefinite"/>
              </circle>
              <circle cx="450" cy="40" r="1.2" fill="#CFA98E" opacity="0.5">
                <animate attributeName="opacity" values="0.1;0.8;0.1" dur="3.5s" repeatCount="indefinite"/>
              </circle>
              <circle cx="600" cy="70" r="1" fill="#E6B59A" opacity="0.9">
                <animate attributeName="opacity" values="0.3;1;0.3" dur="2.8s" repeatCount="indefinite"/>
              </circle>
              <circle cx="700" cy="45" r="1.3" fill="#F1D3BF" opacity="0.6">
                <animate attributeName="opacity" values="0.2;0.7;0.2" dur="4.2s" repeatCount="indefinite"/>
              </circle>
            </g>
            
            <!-- Contribution Galaxy Spiral -->
            <g id="galaxy" transform="translate(400,200)">
              <!-- Central Core -->
              <circle cx="0" cy="0" r="8" fill="url(#starGlow)" filter="url(#glow)">
                <animate attributeName="r" values="6;10;6" dur="4s" repeatCount="indefinite"/>
              </circle>
              
              <!-- Spiral Arms with Contribution Data -->
              <g id="spiral1" transform-origin="0 0">
                <animateTransform attributeName="transform" type="rotate" values="0;360" dur="20s" repeatCount="indefinite"/>
                
                <!-- Contribution Planets -->
                <circle cx="30" cy="0" r="3" fill="#CFA98E" filter="url(#twinkle)">
                  <animate attributeName="r" values="2;4;2" dur="3s" repeatCount="indefinite"/>
                </circle>
                <circle cx="50" cy="10" r="4" fill="#E6B59A" filter="url(#twinkle)">
                  <animate attributeName="r" values="3;5;3" dur="2.5s" repeatCount="indefinite"/>
                </circle>
                <circle cx="70" cy="-5" r="2.5" fill="#F1D3BF" filter="url(#twinkle)">
                  <animate attributeName="r" values="2;3.5;2" dur="3.5s" repeatCount="indefinite"/>
                </circle>
                <circle cx="90" cy="15" r="5" fill="#CFA98E" filter="url(#twinkle)">
                  <animate attributeName="r" values="4;6;4" dur="2.8s" repeatCount="indefinite"/>
                </circle>
                <circle cx="110" cy="-10" r="3.5" fill="#E6B59A" filter="url(#twinkle)">
                  <animate attributeName="r" values="3;4.5;3" dur="4s" repeatCount="indefinite"/>
                </circle>
              </g>
              
              <g id="spiral2" transform-origin="0 0">
                <animateTransform attributeName="transform" type="rotate" values="120;480" dur="20s" repeatCount="indefinite"/>
                
                <circle cx="35" cy="5" r="2.8" fill="#F1D3BF" filter="url(#twinkle)">
                  <animate attributeName="r" values="2.5;3.5;2.5" dur="3.2s" repeatCount="indefinite"/>
                </circle>
                <circle cx="55" cy="-8" r="4.2" fill="#CFA98E" filter="url(#twinkle)">
                  <animate attributeName="r" values="3.5;5;3.5" dur="2.7s" repeatCount="indefinite"/>
                </circle>
                <circle cx="75" cy="12" r="3" fill="#E6B59A" filter="url(#twinkle)">
                  <animate attributeName="r" values="2.8;3.8;2.8" dur="3.8s" repeatCount="indefinite"/>
                </circle>
                <circle cx="95" cy="-3" r="2.2" fill="#F1D3BF" filter="url(#twinkle)">
                  <animate attributeName="r" values="2;3;2" dur="4.5s" repeatCount="indefinite"/>
                </circle>
              </g>
              
              <g id="spiral3" transform-origin="0 0">
                <animateTransform attributeName="transform" type="rotate" values="240;600" dur="20s" repeatCount="indefinite"/>
                
                <circle cx="40" cy="-12" r="3.5" fill="#CFA98E" filter="url(#twinkle)">
                  <animate attributeName="r" values="3;4.5;3" dur="2.9s" repeatCount="indefinite"/>
                </circle>
                <circle cx="60" cy="8" r="2.7" fill="#E6B59A" filter="url(#twinkle)">
                  <animate attributeName="r" values="2.5;3.5;2.5" dur="3.6s" repeatCount="indefinite"/>
                </circle>
                <circle cx="80" cy="-15" r="4.8" fill="#F1D3BF" filter="url(#twinkle)">
                  <animate attributeName="r" values="4;5.5;4" dur="2.4s" repeatCount="indefinite"/>
                </circle>
                <circle cx="100" cy="6" r="3.2" fill="#CFA98E" filter="url(#twinkle)">
                  <animate attributeName="r" values="3;4;3" dur="3.3s" repeatCount="indefinite"/>
                </circle>
              </g>
            </g>
            
            <!-- Floating Code Particles -->
            <g id="codeParticles">
              <text x="150" y="150" fill="#CFA98E" font-family="monospace" font-size="12" opacity="0.7">
                { }
                <animateTransform attributeName="transform" type="translate" values="0,0; 50,-30; 0,0" dur="8s" repeatCount="indefinite"/>
                <animate attributeName="opacity" values="0.3;0.9;0.3" dur="8s" repeatCount="indefinite"/>
              </text>
              
              <text x="600" y="300" fill="#E6B59A" font-family="monospace" font-size="10" opacity="0.6">
                &lt;/&gt;
                <animateTransform attributeName="transform" type="translate" values="0,0; -40,25; 0,0" dur="6s" repeatCount="indefinite"/>
                <animate attributeName="opacity" values="0.2;0.8;0.2" dur="6s" repeatCount="indefinite"/>
              </text>
              
              <text x="100" y="320" fill="#F1D3BF" font-family="monospace" font-size="14" opacity="0.8">
                ()
                <animateTransform attributeName="transform" type="translate" values="0,0; 30,-20; 0,0" dur="7s" repeatCount="indefinite"/>
                <animate attributeName="opacity" values="0.4;1;0.4" dur="7s" repeatCount="indefinite"/>
              </text>
              
              <text x="650" y="120" fill="#CFA98E" font-family="monospace" font-size="11" opacity="0.5">
                []
                <animateTransform attributeName="transform" type="translate" values="0,0; -25,35; 0,0" dur="9s" repeatCount="indefinite"/>
                <animate attributeName="opacity" values="0.2;0.7;0.2" dur="9s" repeatCount="indefinite"/>
              </text>
            </g>
            
            <!-- Title -->
            <text x="400" y="30" text-anchor="middle" fill="#F1D3BF" font-family="Arial, sans-serif" font-size="18" font-weight="bold" filter="url(#glow)">
              Contribution Galaxy
              <animate attributeName="opacity" values="0.8;1;0.8" dur="3s" repeatCount="indefinite"/>
            </text>
            
            <!-- Subtitle -->
            <text x="400" y="380" text-anchor="middle" fill="#CFA98E" font-family="Arial, sans-serif" font-size="12" opacity="0.8">
              Where Code Becomes Stardust ✨
              <animate attributeName="opacity" values="0.6;1;0.6" dur="4s" repeatCount="indefinite"/>
            </text>
          </svg>
          EOF
          
      - name: Publish to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
