name: Generate Simple Contribution Visualization

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Animated Contribution Visualization
        uses: Platane/snk@v3
        with:
          github_user_name: AashishThakuri
          outputs: |
            dist/contribution-animation.svg
            dist/contribution-animation-dark.svg?palette=github-dark
            
      - name: Generate Custom Wave Animation
        run: |
          mkdir -p dist
          cat > dist/wave-contribution.svg << 'EOF'
          <svg width="854" height="200" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="waveGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" style="stop-color:#CFA98E;stop-opacity:1" />
                <stop offset="50%" style="stop-color:#E6B59A;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#F1D3BF;stop-opacity:1" />
              </linearGradient>
              
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge> 
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            
            <rect width="854" height="200" fill="#0D1117"/>
            
            <!-- Animated Wave -->
            <path d="M0,100 Q213,50 427,100 T854,100 L854,200 L0,200 Z" fill="url(#waveGradient)" opacity="0.6" filter="url(#glow)">
              <animate attributeName="d" 
                values="M0,100 Q213,50 427,100 T854,100 L854,200 L0,200 Z;
                        M0,100 Q213,150 427,100 T854,100 L854,200 L0,200 Z;
                        M0,100 Q213,50 427,100 T854,100 L854,200 L0,200 Z" 
                dur="4s" repeatCount="indefinite"/>
            </path>
            
            <!-- Floating Particles -->
            <circle cx="100" cy="80" r="3" fill="#CFA98E" opacity="0.8">
              <animate attributeName="cy" values="80;60;80" dur="3s" repeatCount="indefinite"/>
              <animate attributeName="opacity" values="0.8;0.3;0.8" dur="3s" repeatCount="indefinite"/>
            </circle>
            
            <circle cx="300" cy="120" r="2" fill="#E6B59A" opacity="0.7">
              <animate attributeName="cy" values="120;100;120" dur="4s" repeatCount="indefinite"/>
              <animate attributeName="opacity" values="0.7;0.2;0.7" dur="4s" repeatCount="indefinite"/>
            </circle>
            
            <circle cx="500" cy="90" r="4" fill="#F1D3BF" opacity="0.9">
              <animate attributeName="cy" values="90;70;90" dur="2.5s" repeatCount="indefinite"/>
              <animate attributeName="opacity" values="0.9;0.4;0.9" dur="2.5s" repeatCount="indefinite"/>
            </circle>
            
            <circle cx="700" cy="110" r="2.5" fill="#CFA98E" opacity="0.6">
              <animate attributeName="cy" values="110;90;110" dur="3.5s" repeatCount="indefinite"/>
              <animate attributeName="opacity" values="0.6;0.1;0.6" dur="3.5s" repeatCount="indefinite"/>
            </circle>
            
            <!-- Title -->
            <text x="427" y="30" text-anchor="middle" fill="#F1D3BF" font-family="Arial, sans-serif" font-size="18" font-weight="bold">
              Contribution Wave
              <animate attributeName="opacity" values="0.8;1;0.8" dur="2s" repeatCount="indefinite"/>
            </text>
          </svg>
          EOF
          
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
