name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (for workspace)
        uses: actions/checkout@v4
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: AashishThakuri
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif
            dist/snake-dark.gif?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Pages branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
