name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: AashishThakuri
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Publish to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
